# include "patient_account.h"
# include <iostream>

Patient_account::Patient_account(int day, int room)
{
	days = day;
	rate = 0;
	
	// Hospital Room Types 
	// (1)General Ward				:1000
	// (2)Triple Room				:1800
	// (3)Double Room				:2500
	// (4)Single Room				:4500
	// (5)Intensive Care Unit(ICU)	:10000
	// ==========================================================
	// > data generated by ChatGPT with reference to real-world
	// > https://chatgpt.com/s/t_69d66baec2c48191a0832eafce24a053
	
	if (room == 1) rate = 1000;
	else if (room == 2) rate = 1800;
	else if (room == 3) rate = 2500;
	else if (room == 4) rate = 4500;
	else if (room == 5) rate = 10000;
	else rate = 0;
	
	total = days * rate;
}

void Patient_account::days_cal(int d, int r)
{
	if (r == 1) rate = 1000;
	else if (r == 2) rate = 1800;
	else if (r == 3) rate = 2500;
	else if (r == 4) rate = 4500;
	else if (r == 5) rate = 10000;
	else rate = 0;
	
	days += d;
	total += d * rate;
}

void Patient_account::fee_cal(int f)
{
	total += f;
}

int Patient_account::get_days() const
{
	return days;
}

int Patient_account::get_rate() const
{
	return rate;
}
int Patient_account::get_total() const
{
	return total;
}
