# include "pharmacy.h"

int Pharmacy::get_cost(int type)
{
	// Pharmacy Types
	// (1)Acetaminophen	:180
	// (2)Ibuprofen		:150
	// (3)Antacid		:120
	// (4)Antihistamine	:100
	// (5)Cold Medicine	:200
	// ==========================================================
	// > data generated by ChatGPT with reference to real-world
	// > https://chatgpt.com/s/t_69d66c11cf7c81919b1d977f24aee674
	// > https://chatgpt.com/s/t_69d66bfe60ac8191a62032a30557422b
	
	if (type == 1) return 480;
	else if (type == 2) return 150;
	else if (type == 3) return 120;
	else if (type == 4) return 100;
	else if (type == 5) return 200;
	else return 0;
}
