# include "surgery.h"

int Surgery::get_cost(int type)
{
	// Surgery Types
	// (1)Cataract Surgery			:50000
	// (2)Cesarean Section			:35000
	// (3)Appendectomy				:60000
	// (4)Knee Replacement Surgery	:150000
	// (5)Laser Eye Surgery			:80000
	// ==========================================================
	// > data generated by ChatGPT with reference to real-world
	// > https://chatgpt.com/s/t_69d66c30b3c88191a1bda3bd289cbedb
	// > https://chatgpt.com/s/t_69d66bfe60ac8191a62032a30557422b

	if (type == 1) return 50000;
	else if (type == 2) return 35000;
	else if (type == 3) return 60000;
	else if (type == 4) return 150000;
	else if (type == 5) return 80000;
	else return 0;
}
